# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76637adc57b8e35194826a14e233578ee06ff0579ffad62940edb79dfb2f4955767f218f4b2da14e201f91e44cd4fa4b78a88ae5f44fbaae73d3e1fc799bb9be

test:
  secret_key_base: 621adab96affc7aa79ec44b6b1924a5e2a670c85f3e60471791b7c196e8fc8c527d98360a8ba39984e70d9d2a022254162d7760fed5b2e49c834e03919f046fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
